# Generated by Django 4.2.10 on 2024-08-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscription_course_subscription_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='balance_user',
        ),
    ]
