# Generated by Django 4.2.10 on 2024-08-17 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_lessons_alter_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lessons',
        ),
    ]
