# Generated by Django 4.2.10 on 2024-08-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='courses_lessons', to='courses.lesson', verbose_name='Уроки'),
        ),
    ]
