# Generated by Django 4.2.10 on 2024-08-18 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_remove_course_lessons_alter_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students_count',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(default=0, related_name='students_course', to=settings.AUTH_USER_MODEL, verbose_name='Студенты курса'),
        ),
    ]
